language: php

php:
  - 5.6
  - 7.3
  - hhvm

before_script:
  - composer self-update

install: composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run -v

notifications:
  email: js@jslejko.com
