language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update

install: composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run -v

notifications:
  email: js@jslejko.com
